### ISSUE TITLE
PHISHING

### ISSUE THREAD

**Issue by pointpointclick** [firebase/firebaseui-web#301]
- require email verification...
- use email sign up flow... 
- enter target's email address...
- enter full name `Firstname McLastname click my link http://urlwithbadstuff.com`
- target receives email that includes `Hello Firstname McLastname click my link http://urlwithbadstuff.com`
- target receives email, target's email client converts string `http://urlwithbadstuff.com` to clickable link
- I'm sure you'll agree that's no good.
- Hmmm... ok. Maybe not require the name field? Nope! Can't do that... 
- ok... Maybe you can edit the email template? Nope! Can't do that, either...

I see three possible ways to fix it
1) sanitize the name
2) remove full name field, or allow customer to via config
3) allow editing of email templates

**Comment by supernothing** [comment]
To loosely quote Monty Python, three is right out! Definitely not gonna get fixed in time, and Firebase needs to do that.

Number one cannot happen without server side intervention, which means GAE is posting all the signups back to Firebase. 1.) Ew and 2.) I'm not sure how much that screws with our workflow, but that's why we initially discounted it.

Two is the only one I'm not sure of. Can we do a Firebase signup without a name? Sure, it'll create a broken email verification message, but better than the alternative.

All this sort of jumps around the point though: we have 12k+ emails that we have not verified, and any alteration to our signup process won't change that. If we're trying to verify all of these before the sale, we need a solution outside Firebase I think.

**Comment by bojeil-google** [comment]
FirebaseUI doesn't send any email verifications yet.

We don't currently allow customization of all email templates due to possible abuse and spamming.

Display names are html escaped in email templates. However, thanks for pointing out this issue with links when it comes to display name. We will work on a fix.

If you are worried about sanitizing the display name, you have full control over that as you have access to the user. You can always check `currentUser.displayName` and call `updateProfile` before sending the email.

**Comment by bojeil-google** [comment]
You can also remove display name requirement in FirebaseUI. Check:
https://github.com/firebase/firebaseui-web#configure-email-provider

**Comment by manterfield** [comment]
@nicolasgarnier Hey, I see this was closed as completed but can't see any reason why?

As far as I can tell this still exists as a problem. Signups are able to send malicious links in display name that will be rendered as clickable links in the email.

**Comment by OttlikG** [comment]
When entering `https://google.com` it sanitise it correctly but when I enter `evil.com` it passes through so in the verification email I can click on the link.
I was also trying to create a `beforeCreate` function to hook in with Firebase, but apparently displayName doesn't come through. I think this is due to the fact that you have to update displayName after the user was created. So couldn't do a server side sanitisation.

What would be the ideal solution for this?
