### ISSUE TITLE
Facebook login fails in demo

### ISSUE THREAD

**Issue by mesqueeb** [firebase/firebaseui-web#340]
https://fir-ui-demo-84a6c.firebaseapp.com
When I click on facebook I get:

> App Not Setup: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions.

**Comment by bojeil-google** [comment]
Thanks for reporting this issue. It should be fixed now.

**Comment by ubragg** [comment]
This issue seems to have resurfaced.  I'm seeing this in the demo app again.

**Comment by bojeil-google** [comment]
Hey @ubragg I just tried to sign in with Facebook in the test app. It seems to be working fine.

**Comment by ubragg** [comment]
Hmm, still broken for me.  Here's a screenshot after clicking on the Facebook button:

![Screen Shot 2020-08-20 at 10 44 17 AM](https://user-images.githubusercontent.com/1361365/90806705-406b3a00-e2d2-11ea-998e-7629504735a8.png)

**Comment by bojeil-google** [comment]
Can you try again? Someone switched the Facebook app to dev mode and i switched it back to prod. I was signing in as owner of the account which is why I couldn't see the error.

**Comment by ubragg** [comment]
It works now!  Thanks for the quick fix.

**Comment by bojeil-google** [comment]
Thanks for notifying us about it.
